/**
 * Generates 20px AVIF blur placeholders (LQIPs) for all portfolio images.
 * Reads existing 800w AVIF files from public/portfolio/
 * Writes app/portfolio/lqip.ts — a keyed map used by PortfolioPicture.
 *
 * Key format: /portfolio/{project}/{type}/{slug}
 * e.g. /portfolio/modesto/renders/01-1600.avif → key /portfolio/modesto/renders/01
 */
import * as path from 'path';
import * as fs from 'fs/promises';
import sharp from 'sharp';

const PUBLIC_DIR = path.resolve('public/portfolio');
const OUT_PATH = path.resolve('app/portfolio/lqip.ts');

async function findSmallestAvifs(): Promise<string[]> {
  const files: string[] = [];

  async function walk(dir: string) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (entry.isFile() && entry.name.endsWith('.avif')) {
        // Prefer the smallest (800w) variant as LQIP source
        if (/-800\.avif$/.test(entry.name)) {
          files.push(full);
        }
      }
    }
  }

  await walk(PUBLIC_DIR);
  return files.sort();
}

function toPublicPath(absPath: string): string {
  return absPath
    .replace(path.resolve('public'), '')
    .replace(/\\/g, '/');
}

/** /portfolio/modesto/renders/01-800.avif → /portfolio/modesto/renders/01 */
function toKey(pubPath: string): string {
  return pubPath.replace(/-\d+\.avif$/, '');
}

async function buildLqip(filePath: string): Promise<string> {
  const buf = await sharp(filePath)
    .resize(20)
    .blur(2)
    .avif({ quality: 25 })
    .toBuffer();
  return `data:image/avif;base64,${buf.toString('base64')}`;
}

async function main() {
  const files = await findSmallestAvifs();
  console.log(`[build-lqip] Processing ${files.length} images…`);

  const entries: string[] = [];

  for (const file of files) {
    const pub = toPublicPath(file);
    const key = toKey(pub);
    const dataUri = await buildLqip(file);
    entries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(dataUri)}`);
    process.stdout.write('.');
  }

  console.log(`\n[build-lqip] Writing ${OUT_PATH}…`);

  const content = [
    '// AUTO-GENERATED by scripts/build-lqip.ts — do not hand-edit.',
    '// Key: /portfolio/{project}/{type}/{slug} (without -{w}.avif suffix)',
    'export const lqipMap: Record<string, string> = {',
    entries.join(',\n'),
    '};',
    '',
  ].join('\n');

  await fs.writeFile(OUT_PATH, content, 'utf8');
  console.log(`[build-lqip] Done — ${files.length} LQIPs written.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
