// AUTO-GENERATED by scripts/build-portfolio-assets.ts — do not hand-edit.
// ResponsiveImage.avif/.webp/.jpg → largest variant (2400w renders, 1600w before/construction).
// srcsetAvif/srcsetWebp/srcsetJpg → full srcset strings for <source srcset> usage.

export type ResponsiveImage = {
  avif: string;
  webp: string;
  jpg: string;
  width: number;
  height: number;
  alt: string;
  srcsetAvif: string;
  srcsetWebp: string;
  srcsetJpg: string;
  /** 20px AVIF blur data URI for LQIP placeholder. Optional — generated by build-lqip.ts. */
  base64Lqip?: string;
};

export type ProjectVideo = {
  mp4: string;
  webm: string;
  poster: string;
  width: number;
  height: number;
};

export type ProjectAssets = {
  before: ResponsiveImage[];
  construction: ResponsiveImage[];
  renders: ResponsiveImage[];
  videos: ProjectVideo[];
  heroLoop?: ProjectVideo;
};

export type AssetKey = 'modesto' | 'livermore' | 'sacramento';

export const portfolioAssets: Record<AssetKey, ProjectAssets> = {
  modesto: {
    before: [
    {
      avif: "/portfolio/modesto/before/01-1600.avif",
      webp: "/portfolio/modesto/before/01-1600.webp",
      jpg: "/portfolio/modesto/before/01-1600.jpg",
      width: 1200,
      height: 1600,
      alt: "Pre-construction site photo for Chocolate Fish Cafe Modesto California 3D visualization project, view 1",
      srcsetAvif: "/portfolio/modesto/before/01-1600.avif 1600w, /portfolio/modesto/before/01-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/before/01-1600.webp 1600w, /portfolio/modesto/before/01-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/before/01-1600.jpg 1600w, /portfolio/modesto/before/01-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/before/02-1600.avif",
      webp: "/portfolio/modesto/before/02-1600.webp",
      jpg: "/portfolio/modesto/before/02-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Pre-construction site photo for Chocolate Fish Cafe Modesto California 3D visualization project, view 2",
      srcsetAvif: "/portfolio/modesto/before/02-1600.avif 1600w, /portfolio/modesto/before/02-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/before/02-1600.webp 1600w, /portfolio/modesto/before/02-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/before/02-1600.jpg 1600w, /portfolio/modesto/before/02-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/before/03-1600.avif",
      webp: "/portfolio/modesto/before/03-1600.webp",
      jpg: "/portfolio/modesto/before/03-1600.jpg",
      width: 1200,
      height: 1600,
      alt: "Pre-construction site photo for Chocolate Fish Cafe Modesto California 3D visualization project, view 3",
      srcsetAvif: "/portfolio/modesto/before/03-1600.avif 1600w, /portfolio/modesto/before/03-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/before/03-1600.webp 1600w, /portfolio/modesto/before/03-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/before/03-1600.jpg 1600w, /portfolio/modesto/before/03-800.jpg 800w",
    }
    ],
    construction: [
    {
      avif: "/portfolio/modesto/construction/01-1600.avif",
      webp: "/portfolio/modesto/construction/01-1600.webp",
      jpg: "/portfolio/modesto/construction/01-1600.jpg",
      width: 1200,
      height: 1600,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Modesto California 3D interior render, view 1",
      srcsetAvif: "/portfolio/modesto/construction/01-1600.avif 1600w, /portfolio/modesto/construction/01-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/construction/01-1600.webp 1600w, /portfolio/modesto/construction/01-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/construction/01-1600.jpg 1600w, /portfolio/modesto/construction/01-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/construction/02-1600.avif",
      webp: "/portfolio/modesto/construction/02-1600.webp",
      jpg: "/portfolio/modesto/construction/02-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Modesto California 3D interior render, view 2",
      srcsetAvif: "/portfolio/modesto/construction/02-1600.avif 1600w, /portfolio/modesto/construction/02-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/construction/02-1600.webp 1600w, /portfolio/modesto/construction/02-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/construction/02-1600.jpg 1600w, /portfolio/modesto/construction/02-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/construction/03-1600.avif",
      webp: "/portfolio/modesto/construction/03-1600.webp",
      jpg: "/portfolio/modesto/construction/03-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Modesto California 3D interior render, view 3",
      srcsetAvif: "/portfolio/modesto/construction/03-1600.avif 1600w, /portfolio/modesto/construction/03-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/construction/03-1600.webp 1600w, /portfolio/modesto/construction/03-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/construction/03-1600.jpg 1600w, /portfolio/modesto/construction/03-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/construction/04-1600.avif",
      webp: "/portfolio/modesto/construction/04-1600.webp",
      jpg: "/portfolio/modesto/construction/04-1600.jpg",
      width: 1200,
      height: 1600,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Modesto California 3D interior render, view 4",
      srcsetAvif: "/portfolio/modesto/construction/04-1600.avif 1600w, /portfolio/modesto/construction/04-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/construction/04-1600.webp 1600w, /portfolio/modesto/construction/04-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/construction/04-1600.jpg 1600w, /portfolio/modesto/construction/04-800.jpg 800w",
    }
    ],
    renders: [
    {
      avif: "/portfolio/modesto/renders/01-2400.avif",
      webp: "/portfolio/modesto/renders/01-2400.webp",
      jpg: "/portfolio/modesto/renders/01-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D interior render of Chocolate Fish Cafe Modesto California, view 1",
      srcsetAvif: "/portfolio/modesto/renders/01-2400.avif 2400w, /portfolio/modesto/renders/01-1600.avif 1600w, /portfolio/modesto/renders/01-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/renders/01-2400.webp 2400w, /portfolio/modesto/renders/01-1600.webp 1600w, /portfolio/modesto/renders/01-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/renders/01-2400.jpg 2400w, /portfolio/modesto/renders/01-1600.jpg 1600w, /portfolio/modesto/renders/01-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/renders/02-2400.avif",
      webp: "/portfolio/modesto/renders/02-2400.webp",
      jpg: "/portfolio/modesto/renders/02-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D interior render of Chocolate Fish Cafe Modesto California, view 2",
      srcsetAvif: "/portfolio/modesto/renders/02-2400.avif 2400w, /portfolio/modesto/renders/02-1600.avif 1600w, /portfolio/modesto/renders/02-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/renders/02-2400.webp 2400w, /portfolio/modesto/renders/02-1600.webp 1600w, /portfolio/modesto/renders/02-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/renders/02-2400.jpg 2400w, /portfolio/modesto/renders/02-1600.jpg 1600w, /portfolio/modesto/renders/02-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/renders/03-2400.avif",
      webp: "/portfolio/modesto/renders/03-2400.webp",
      jpg: "/portfolio/modesto/renders/03-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D interior render of Chocolate Fish Cafe Modesto California, view 3",
      srcsetAvif: "/portfolio/modesto/renders/03-2400.avif 2400w, /portfolio/modesto/renders/03-1600.avif 1600w, /portfolio/modesto/renders/03-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/renders/03-2400.webp 2400w, /portfolio/modesto/renders/03-1600.webp 1600w, /portfolio/modesto/renders/03-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/renders/03-2400.jpg 2400w, /portfolio/modesto/renders/03-1600.jpg 1600w, /portfolio/modesto/renders/03-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/renders/04-2400.avif",
      webp: "/portfolio/modesto/renders/04-2400.webp",
      jpg: "/portfolio/modesto/renders/04-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D interior render of Chocolate Fish Cafe Modesto California, view 4",
      srcsetAvif: "/portfolio/modesto/renders/04-2400.avif 2400w, /portfolio/modesto/renders/04-1600.avif 1600w, /portfolio/modesto/renders/04-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/renders/04-2400.webp 2400w, /portfolio/modesto/renders/04-1600.webp 1600w, /portfolio/modesto/renders/04-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/renders/04-2400.jpg 2400w, /portfolio/modesto/renders/04-1600.jpg 1600w, /portfolio/modesto/renders/04-800.jpg 800w",
    },
    {
      avif: "/portfolio/modesto/renders/05-2400.avif",
      webp: "/portfolio/modesto/renders/05-2400.webp",
      jpg: "/portfolio/modesto/renders/05-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D interior render of Chocolate Fish Cafe Modesto California, view 5",
      srcsetAvif: "/portfolio/modesto/renders/05-2400.avif 2400w, /portfolio/modesto/renders/05-1600.avif 1600w, /portfolio/modesto/renders/05-800.avif 800w",
      srcsetWebp: "/portfolio/modesto/renders/05-2400.webp 2400w, /portfolio/modesto/renders/05-1600.webp 1600w, /portfolio/modesto/renders/05-800.webp 800w",
      srcsetJpg: "/portfolio/modesto/renders/05-2400.jpg 2400w, /portfolio/modesto/renders/05-1600.jpg 1600w, /portfolio/modesto/renders/05-800.jpg 800w",
    }
    ],
    videos: [
    {
      mp4: "/portfolio/modesto/videos/walkthrough-01.mp4",
      webm: "/portfolio/modesto/videos/walkthrough-01.webm",
      poster: "/portfolio/modesto/videos/walkthrough-01.poster.webp",
      width: 1920,
      height: 1080,
    },
    {
      mp4: "/portfolio/modesto/videos/walkthrough-02.mp4",
      webm: "/portfolio/modesto/videos/walkthrough-02.webm",
      poster: "/portfolio/modesto/videos/walkthrough-02.poster.webp",
      width: 1920,
      height: 1080,
    },
    {
      mp4: "/portfolio/modesto/videos/walkthrough-03.mp4",
      webm: "/portfolio/modesto/videos/walkthrough-03.webm",
      poster: "/portfolio/modesto/videos/walkthrough-03.poster.webp",
      width: 1920,
      height: 1080,
    }
    ],
    heroLoop: {
      mp4: "/portfolio/modesto/videos/walkthrough-03.mp4",
      webm: "/portfolio/modesto/videos/walkthrough-03.webm",
      poster: "/portfolio/modesto/videos/walkthrough-03.poster.webp",
      width: 1920,
      height: 1080,
    },
  },
  livermore: {
    before: [

    ],
    construction: [
    {
      avif: "/portfolio/livermore/construction/01-1600.avif",
      webp: "/portfolio/livermore/construction/01-1600.webp",
      jpg: "/portfolio/livermore/construction/01-1600.jpg",
      width: 1024,
      height: 768,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Livermore California 3D architectural render, view 1",
      srcsetAvif: "/portfolio/livermore/construction/01-1600.avif 1600w, /portfolio/livermore/construction/01-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/construction/01-1600.webp 1600w, /portfolio/livermore/construction/01-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/construction/01-1600.jpg 1600w, /portfolio/livermore/construction/01-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/construction/02-1600.avif",
      webp: "/portfolio/livermore/construction/02-1600.webp",
      jpg: "/portfolio/livermore/construction/02-1600.jpg",
      width: 1024,
      height: 768,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Livermore California 3D architectural render, view 2",
      srcsetAvif: "/portfolio/livermore/construction/02-1600.avif 1600w, /portfolio/livermore/construction/02-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/construction/02-1600.webp 1600w, /portfolio/livermore/construction/02-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/construction/02-1600.jpg 1600w, /portfolio/livermore/construction/02-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/construction/03-1600.avif",
      webp: "/portfolio/livermore/construction/03-1600.webp",
      jpg: "/portfolio/livermore/construction/03-1600.jpg",
      width: 1024,
      height: 768,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Livermore California 3D architectural render, view 3",
      srcsetAvif: "/portfolio/livermore/construction/03-1600.avif 1600w, /portfolio/livermore/construction/03-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/construction/03-1600.webp 1600w, /portfolio/livermore/construction/03-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/construction/03-1600.jpg 1600w, /portfolio/livermore/construction/03-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/construction/04-1600.avif",
      webp: "/portfolio/livermore/construction/04-1600.webp",
      jpg: "/portfolio/livermore/construction/04-1600.jpg",
      width: 768,
      height: 1024,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Livermore California 3D architectural render, view 4",
      srcsetAvif: "/portfolio/livermore/construction/04-1600.avif 1600w, /portfolio/livermore/construction/04-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/construction/04-1600.webp 1600w, /portfolio/livermore/construction/04-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/construction/04-1600.jpg 1600w, /portfolio/livermore/construction/04-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/construction/05-1600.avif",
      webp: "/portfolio/livermore/construction/05-1600.webp",
      jpg: "/portfolio/livermore/construction/05-1600.jpg",
      width: 768,
      height: 1024,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Livermore California 3D architectural render, view 5",
      srcsetAvif: "/portfolio/livermore/construction/05-1600.avif 1600w, /portfolio/livermore/construction/05-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/construction/05-1600.webp 1600w, /portfolio/livermore/construction/05-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/construction/05-1600.jpg 1600w, /portfolio/livermore/construction/05-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/construction/06-1600.avif",
      webp: "/portfolio/livermore/construction/06-1600.webp",
      jpg: "/portfolio/livermore/construction/06-1600.jpg",
      width: 1024,
      height: 768,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Livermore California 3D architectural render, view 6",
      srcsetAvif: "/portfolio/livermore/construction/06-1600.avif 1600w, /portfolio/livermore/construction/06-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/construction/06-1600.webp 1600w, /portfolio/livermore/construction/06-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/construction/06-1600.jpg 1600w, /portfolio/livermore/construction/06-800.jpg 800w",
    }
    ],
    renders: [
    {
      avif: "/portfolio/livermore/renders/01-2400.avif",
      webp: "/portfolio/livermore/renders/01-2400.webp",
      jpg: "/portfolio/livermore/renders/01-2400.jpg",
      width: 2400,
      height: 1350,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Livermore California, view 1",
      srcsetAvif: "/portfolio/livermore/renders/01-2400.avif 2400w, /portfolio/livermore/renders/01-1600.avif 1600w, /portfolio/livermore/renders/01-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/renders/01-2400.webp 2400w, /portfolio/livermore/renders/01-1600.webp 1600w, /portfolio/livermore/renders/01-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/renders/01-2400.jpg 2400w, /portfolio/livermore/renders/01-1600.jpg 1600w, /portfolio/livermore/renders/01-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/renders/02-2400.avif",
      webp: "/portfolio/livermore/renders/02-2400.webp",
      jpg: "/portfolio/livermore/renders/02-2400.jpg",
      width: 1536,
      height: 1024,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Livermore California, view 2",
      srcsetAvif: "/portfolio/livermore/renders/02-2400.avif 2400w, /portfolio/livermore/renders/02-1600.avif 1600w, /portfolio/livermore/renders/02-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/renders/02-2400.webp 2400w, /portfolio/livermore/renders/02-1600.webp 1600w, /portfolio/livermore/renders/02-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/renders/02-2400.jpg 2400w, /portfolio/livermore/renders/02-1600.jpg 1600w, /portfolio/livermore/renders/02-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/renders/03-2400.avif",
      webp: "/portfolio/livermore/renders/03-2400.webp",
      jpg: "/portfolio/livermore/renders/03-2400.jpg",
      width: 2400,
      height: 1350,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Livermore California, view 3",
      srcsetAvif: "/portfolio/livermore/renders/03-2400.avif 2400w, /portfolio/livermore/renders/03-1600.avif 1600w, /portfolio/livermore/renders/03-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/renders/03-2400.webp 2400w, /portfolio/livermore/renders/03-1600.webp 1600w, /portfolio/livermore/renders/03-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/renders/03-2400.jpg 2400w, /portfolio/livermore/renders/03-1600.jpg 1600w, /portfolio/livermore/renders/03-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/renders/04-2400.avif",
      webp: "/portfolio/livermore/renders/04-2400.webp",
      jpg: "/portfolio/livermore/renders/04-2400.jpg",
      width: 1536,
      height: 1024,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Livermore California, view 4",
      srcsetAvif: "/portfolio/livermore/renders/04-2400.avif 2400w, /portfolio/livermore/renders/04-1600.avif 1600w, /portfolio/livermore/renders/04-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/renders/04-2400.webp 2400w, /portfolio/livermore/renders/04-1600.webp 1600w, /portfolio/livermore/renders/04-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/renders/04-2400.jpg 2400w, /portfolio/livermore/renders/04-1600.jpg 1600w, /portfolio/livermore/renders/04-800.jpg 800w",
    },
    {
      avif: "/portfolio/livermore/renders/05-2400.avif",
      webp: "/portfolio/livermore/renders/05-2400.webp",
      jpg: "/portfolio/livermore/renders/05-2400.jpg",
      width: 1920,
      height: 1080,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Livermore California, view 5",
      srcsetAvif: "/portfolio/livermore/renders/05-2400.avif 2400w, /portfolio/livermore/renders/05-1600.avif 1600w, /portfolio/livermore/renders/05-800.avif 800w",
      srcsetWebp: "/portfolio/livermore/renders/05-2400.webp 2400w, /portfolio/livermore/renders/05-1600.webp 1600w, /portfolio/livermore/renders/05-800.webp 800w",
      srcsetJpg: "/portfolio/livermore/renders/05-2400.jpg 2400w, /portfolio/livermore/renders/05-1600.jpg 1600w, /portfolio/livermore/renders/05-800.jpg 800w",
    }
    ],
    videos: [

    ],
  },
  sacramento: {
    before: [

    ],
    construction: [
    {
      avif: "/portfolio/sacramento/construction/01-1600.avif",
      webp: "/portfolio/sacramento/construction/01-1600.webp",
      jpg: "/portfolio/sacramento/construction/01-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 1",
      srcsetAvif: "/portfolio/sacramento/construction/01-1600.avif 1600w, /portfolio/sacramento/construction/01-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/01-1600.webp 1600w, /portfolio/sacramento/construction/01-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/01-1600.jpg 1600w, /portfolio/sacramento/construction/01-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/02-1600.avif",
      webp: "/portfolio/sacramento/construction/02-1600.webp",
      jpg: "/portfolio/sacramento/construction/02-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 2",
      srcsetAvif: "/portfolio/sacramento/construction/02-1600.avif 1600w, /portfolio/sacramento/construction/02-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/02-1600.webp 1600w, /portfolio/sacramento/construction/02-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/02-1600.jpg 1600w, /portfolio/sacramento/construction/02-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/03-1600.avif",
      webp: "/portfolio/sacramento/construction/03-1600.webp",
      jpg: "/portfolio/sacramento/construction/03-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 3",
      srcsetAvif: "/portfolio/sacramento/construction/03-1600.avif 1600w, /portfolio/sacramento/construction/03-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/03-1600.webp 1600w, /portfolio/sacramento/construction/03-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/03-1600.jpg 1600w, /portfolio/sacramento/construction/03-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/04-1600.avif",
      webp: "/portfolio/sacramento/construction/04-1600.webp",
      jpg: "/portfolio/sacramento/construction/04-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 4",
      srcsetAvif: "/portfolio/sacramento/construction/04-1600.avif 1600w, /portfolio/sacramento/construction/04-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/04-1600.webp 1600w, /portfolio/sacramento/construction/04-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/04-1600.jpg 1600w, /portfolio/sacramento/construction/04-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/05-1600.avif",
      webp: "/portfolio/sacramento/construction/05-1600.webp",
      jpg: "/portfolio/sacramento/construction/05-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 5",
      srcsetAvif: "/portfolio/sacramento/construction/05-1600.avif 1600w, /portfolio/sacramento/construction/05-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/05-1600.webp 1600w, /portfolio/sacramento/construction/05-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/05-1600.jpg 1600w, /portfolio/sacramento/construction/05-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/06-1600.avif",
      webp: "/portfolio/sacramento/construction/06-1600.webp",
      jpg: "/portfolio/sacramento/construction/06-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 6",
      srcsetAvif: "/portfolio/sacramento/construction/06-1600.avif 1600w, /portfolio/sacramento/construction/06-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/06-1600.webp 1600w, /portfolio/sacramento/construction/06-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/06-1600.jpg 1600w, /portfolio/sacramento/construction/06-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/07-1600.avif",
      webp: "/portfolio/sacramento/construction/07-1600.webp",
      jpg: "/portfolio/sacramento/construction/07-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 7",
      srcsetAvif: "/portfolio/sacramento/construction/07-1600.avif 1600w, /portfolio/sacramento/construction/07-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/07-1600.webp 1600w, /portfolio/sacramento/construction/07-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/07-1600.jpg 1600w, /portfolio/sacramento/construction/07-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/08-1600.avif",
      webp: "/portfolio/sacramento/construction/08-1600.webp",
      jpg: "/portfolio/sacramento/construction/08-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 8",
      srcsetAvif: "/portfolio/sacramento/construction/08-1600.avif 1600w, /portfolio/sacramento/construction/08-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/08-1600.webp 1600w, /portfolio/sacramento/construction/08-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/08-1600.jpg 1600w, /portfolio/sacramento/construction/08-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/09-1600.avif",
      webp: "/portfolio/sacramento/construction/09-1600.webp",
      jpg: "/portfolio/sacramento/construction/09-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 9",
      srcsetAvif: "/portfolio/sacramento/construction/09-1600.avif 1600w, /portfolio/sacramento/construction/09-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/09-1600.webp 1600w, /portfolio/sacramento/construction/09-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/09-1600.jpg 1600w, /portfolio/sacramento/construction/09-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/construction/10-1600.avif",
      webp: "/portfolio/sacramento/construction/10-1600.webp",
      jpg: "/portfolio/sacramento/construction/10-1600.jpg",
      width: 1600,
      height: 1200,
      alt: "Construction progress photo matching the Chocolate Fish Cafe Sacramento California 3D architectural render, view 10",
      srcsetAvif: "/portfolio/sacramento/construction/10-1600.avif 1600w, /portfolio/sacramento/construction/10-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/construction/10-1600.webp 1600w, /portfolio/sacramento/construction/10-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/construction/10-1600.jpg 1600w, /portfolio/sacramento/construction/10-800.jpg 800w",
    }
    ],
    renders: [
    {
      avif: "/portfolio/sacramento/renders/01-2400.avif",
      webp: "/portfolio/sacramento/renders/01-2400.webp",
      jpg: "/portfolio/sacramento/renders/01-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Sacramento California, view 1",
      srcsetAvif: "/portfolio/sacramento/renders/01-2400.avif 2400w, /portfolio/sacramento/renders/01-1600.avif 1600w, /portfolio/sacramento/renders/01-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/renders/01-2400.webp 2400w, /portfolio/sacramento/renders/01-1600.webp 1600w, /portfolio/sacramento/renders/01-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/renders/01-2400.jpg 2400w, /portfolio/sacramento/renders/01-1600.jpg 1600w, /portfolio/sacramento/renders/01-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/renders/02-2400.avif",
      webp: "/portfolio/sacramento/renders/02-2400.webp",
      jpg: "/portfolio/sacramento/renders/02-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Sacramento California, view 2",
      srcsetAvif: "/portfolio/sacramento/renders/02-2400.avif 2400w, /portfolio/sacramento/renders/02-1600.avif 1600w, /portfolio/sacramento/renders/02-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/renders/02-2400.webp 2400w, /portfolio/sacramento/renders/02-1600.webp 1600w, /portfolio/sacramento/renders/02-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/renders/02-2400.jpg 2400w, /portfolio/sacramento/renders/02-1600.jpg 1600w, /portfolio/sacramento/renders/02-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/renders/03-2400.avif",
      webp: "/portfolio/sacramento/renders/03-2400.webp",
      jpg: "/portfolio/sacramento/renders/03-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Sacramento California, view 3",
      srcsetAvif: "/portfolio/sacramento/renders/03-2400.avif 2400w, /portfolio/sacramento/renders/03-1600.avif 1600w, /portfolio/sacramento/renders/03-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/renders/03-2400.webp 2400w, /portfolio/sacramento/renders/03-1600.webp 1600w, /portfolio/sacramento/renders/03-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/renders/03-2400.jpg 2400w, /portfolio/sacramento/renders/03-1600.jpg 1600w, /portfolio/sacramento/renders/03-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/renders/04-2400.avif",
      webp: "/portfolio/sacramento/renders/04-2400.webp",
      jpg: "/portfolio/sacramento/renders/04-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Sacramento California, view 4",
      srcsetAvif: "/portfolio/sacramento/renders/04-2400.avif 2400w, /portfolio/sacramento/renders/04-1600.avif 1600w, /portfolio/sacramento/renders/04-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/renders/04-2400.webp 2400w, /portfolio/sacramento/renders/04-1600.webp 1600w, /portfolio/sacramento/renders/04-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/renders/04-2400.jpg 2400w, /portfolio/sacramento/renders/04-1600.jpg 1600w, /portfolio/sacramento/renders/04-800.jpg 800w",
    },
    {
      avif: "/portfolio/sacramento/renders/05-2400.avif",
      webp: "/portfolio/sacramento/renders/05-2400.webp",
      jpg: "/portfolio/sacramento/renders/05-2400.jpg",
      width: 1672,
      height: 941,
      alt: "Photorealistic 3D architectural render of Chocolate Fish Cafe Sacramento California, view 5",
      srcsetAvif: "/portfolio/sacramento/renders/05-2400.avif 2400w, /portfolio/sacramento/renders/05-1600.avif 1600w, /portfolio/sacramento/renders/05-800.avif 800w",
      srcsetWebp: "/portfolio/sacramento/renders/05-2400.webp 2400w, /portfolio/sacramento/renders/05-1600.webp 1600w, /portfolio/sacramento/renders/05-800.webp 800w",
      srcsetJpg: "/portfolio/sacramento/renders/05-2400.jpg 2400w, /portfolio/sacramento/renders/05-1600.jpg 1600w, /portfolio/sacramento/renders/05-800.jpg 800w",
    }
    ],
    videos: [

    ],
  }
};
